### ISSUE TITLE
Having an issue with crashing at launch (mac)

### ISSUE THREAD

**Issue by Awke666** [MoriyaShiine/extra-origins#126]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/6/21 8:18 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/command/arguments/IArgumentSerializer
	at virtuoel.pehkui.api.ScaleRegistries.create(ScaleRegistries.java:45)
	at virtuoel.pehkui.api.ScaleRegistries.<clinit>(ScaleRegistries.java:20)
	at virtuoel.pehkui.api.ScaleType.<clinit>(ScaleType.java:18)
	at net.minecraft.class_1309.handler$zcb000$tryUseTotem(class_1309.java:3411)
	at net.minecraft.class_1309.method_6095(class_1309.java)
	at net.minecraft.class_1309.method_5643(class_1309.java:1101)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:631)
	at net.minecraft.class_1308.method_6121(class_1308.java:1474)
	at net.minecraft.class_1642.method_6121(class_1642.java:344)
	at net.minecraft.class_1366.method_6288(class_1366.java:142)
	at net.minecraft.class_1366.method_6268(class_1366.java:134)
	at net.minecraft.class_1396.method_6268(class_1396.java:28)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_1355.method_6275(class_1355.java:88)
	at net.minecraft.class_1308.method_6023(class_1308.java:736)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1642.method_6007(class_1642.java:260)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1642.method_5773(class_1642.java:233)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraft.command.arguments.IArgumentSerializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at virtuoel.pehkui.api.ScaleRegistries.create(ScaleRegistries.java:45)
	at virtuoel.pehkui.api.ScaleRegistries.<clinit>(ScaleRegistries.java:20)
	at virtuoel.pehkui.api.ScaleType.<clinit>(ScaleType.java:18)
	at net.minecraft.class_1309.handler$zcb000$tryUseTotem(class_1309.java:3411)
	at net.minecraft.class_1309.method_6095(class_1309.java)
	at net.minecraft.class_1309.method_5643(class_1309.java:1101)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:631)
	at net.minecraft.class_1308.method_6121(class_1308.java:1474)
	at net.minecraft.class_1642.method_6121(class_1642.java:344)
	at net.minecraft.class_1366.method_6288(class_1366.java:142)
	at net.minecraft.class_1366.method_6268(class_1366.java:134)
	at net.minecraft.class_1396.method_6268(class_1396.java:28)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_1355.method_6275(class_1355.java:88)
	at net.minecraft.class_1308.method_6023(class_1308.java:736)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1642.method_6007(class_1642.java:260)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_1642.method_5773(class_1642.java:233)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.class_1642)
	Entity ID: 1150
	Entity Name: Zombie
	Entity's Exact location: -36.52, 64.00, 235.56
	Entity's Block location: World: (-37,64,235), Chunk: (at 11,4,11 in -3,14; contains blocks -48,0,224 to -33,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, -0.06
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Awke_0'/262, l='ServerLevel[New World]', x=-35.91, y=64.00, z=234.44]]
	Chunk stats: ServerChunkCache: 2178
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,65,128), Chunk: (at 0,4,0 in 1,8; contains blocks 16,0,128 to 31,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2065 game time, 18425 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 49275 (now: false), thunder time: 154356 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 933333576 bytes (890 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.14
		fabric: Fabric API 0.33.1+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.4.0
		origins: Origins 0.7.0
		pehkui: Pehkui (Forge Version) 0.0.0+forge
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		slimeorigin: Slimeorigin 3.0.0
		toomanyorigins: TooManyOrigins 0.1.2
	Player Count: 1 / 8; [class_3222['Awke_0'/262, l='ServerLevel[New World]', x=-35.91, y=64.00, z=234.44]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by MoriyaShiine** [comment]
You have Pehkui forge installed, be sure to install the fabric version. Common mistake, don't worry about it haha

**Comment by Awke666** [comment]
ohhh sorry for the troubles and thank you!!
