### ISSUE TITLE
Crash on server startup using Extra Origins

### ISSUE THREAD

**Issue by heyimspook** [MoriyaShiine/extra-origins#185]
### Mod version

extraorigins-1.19-1.jar

### A description of the issue

"java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extraorigins'!
...
Caused by: java.lang.ExceptionInInitializerError
	at moriyashiine.extraorigins.common.ExtraOrigins.onInitialize(ExtraOrigins.java:22) ~[extraorigins-1.19-1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.particle.v1.FabricParticleTypes in environment type SERVER"

Full crash report: https://pastebin.com/PygfRDdE

**Comment by MoriyaShiine** [comment]
Fabric API bug, you just need to update to at least 0.55.3
