### ISSUE TITLE
Inchling size and crashing issues

### ISSUE THREAD

**Issue by chalkychelsea** [MoriyaShiine/extra-origins#19]
I assume it's making the game crash, anyways.
The size issues are certain, however.

At seemingly random intervals, my size will be set back to two blocks, but I'll still have inchling properties. 
Additionally, when I use that orb of change to reset myself back to inchling size, it crashes the game. 

(I don't know if this is related, either, but when I'm playing as an inchling, my head is rendered wrong, making the outer layer of my player's head just. gone.)
Attatched are the crash log and an image example of what happened. 
![unknown](https://user-images.githubusercontent.com/74801289/99863279-6d4a1a00-2b6b-11eb-8046-947bc75c153f.png)
[crash-2020-11-20_19.46.48-client.txt](https://github.com/MoriyaShiine/extra-origins/files/5576777/crash-2020-11-20_19.46.48-client.txt)

**Comment by MoriyaShiine** [comment]
I'm not sure what causes the crash, but the desync is a Pehkui bug [https://github.com/Virtuoel/Pehkui/issues/25](url).

**Comment by epicRedHot** [comment]
A similar situation happened to me, where after re-selecting Inchling while already having it as my active Origin, the game crashed with the message: "java.lang.IllegalArgumentException: Modifier is already applied on this attribute!" (pulled from crash log)

The full crash log is as follows. (apologies for not knowing how to submit this as a link, as this is my first time using GitHub)
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/31/20 8:48 PM
Description: mouseClicked event handler

java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.class_1324.method_6197(class_1324.java:73)
	at net.minecraft.class_1324.method_26835(class_1324.java:81)
	at io.github.apace100.origins.power.AttributePower.lambda$onAdded$0(AttributePower.java:39)
	at io.github.apace100.origins.power.AttributePower$$Lambda$6890/305866233.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.power.AttributePower.onAdded(AttributePower.java:37)
	at io.github.apace100.origins.component.PlayerOriginComponent.lambda$setOrigin$3(PlayerOriginComponent.java:133)
	at io.github.apace100.origins.component.PlayerOriginComponent$$Lambda$6876/1134649268.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.component.PlayerOriginComponent.setOrigin(PlayerOriginComponent.java:129)
	at io.github.apace100.origins.screen.ChooseOriginScreen.lambda$init$4(ChooseOriginScreen.java:113)
	at io.github.apace100.origins.screen.ChooseOriginScreen$$Lambda$6883/921328575.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4170/773209924.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4169/1889552797.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3524/571232922.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1324.method_6197(class_1324.java:73)
	at net.minecraft.class_1324.method_26835(class_1324.java:81)
	at io.github.apace100.origins.power.AttributePower.lambda$onAdded$0(AttributePower.java:39)
	at io.github.apace100.origins.power.AttributePower$$Lambda$6890/305866233.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.power.AttributePower.onAdded(AttributePower.java:37)
	at io.github.apace100.origins.component.PlayerOriginComponent.lambda$setOrigin$3(PlayerOriginComponent.java:133)
	at io.github.apace100.origins.component.PlayerOriginComponent$$Lambda$6876/1134649268.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.component.PlayerOriginComponent.setOrigin(PlayerOriginComponent.java:129)
	at io.github.apace100.origins.screen.ChooseOriginScreen.lambda$init$4(ChooseOriginScreen.java:113)
	at io.github.apace100.origins.screen.ChooseOriginScreen$$Lambda$6883/921328575.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4170/773209924.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: io.github.apace100.origins.screen.ChooseOriginScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4169/1889552797.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3524/571232922.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
	All players: 1 total; [class_746['epicRedHot'/220, l='ClientWorld minecraft:overworld', x=115.55, y=74.00, z=-170.82]]
	Chunk stats: Client Chunks (ImmPtl) 927
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,66,-112), Chunk: (at 0,4,0 in 11,-7; contains blocks 176,0,-112 to 191,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 431652 game time, 109302 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1125698328 bytes (1073 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		artifacts: Artifacts 2.0.2+1.16.4-fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bitsandchisels: BitsAndChisels 1.1.6
		blur: Blur (Fabric) 2.0.0
		caelus: Caelus API 0.0.15-1.16.4
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.3
		darkness: True Darkness 1.6.57
		doorsofinfinity: Doors of Infinity 1.0.8-1.16.3
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		extraorigins: Extra Origins 1.16.4-5
		fabric: Fabric API 0.28.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fabrictailor: Fabric Tailor 1.4.0-1.16.4
		fallflyinglib: FallFlyingLib 1.1.0
		fiber: fiber 0.23.0-2
		icarus: Icarus 1.1
		illuminations: Illuminations 1.4
		imm_ptl_core: Immersive Portals Core 0.55
		immersive_portals: Immersive Portals 0.55
		infinitemusic: Infinite Music 1.3.0
		jankson: Jankson 3.0.1+j1.2.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.1.0+1.16.3
		minecraft: Minecraft 1.16.4
		modid: Damage Tilt 1.16-fabric-0.1.0
		modmenu: Mod Menu 1.14.13+build.19
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		origins: Origins 0.4.4
		particlerain: Particle Rain 1.2.0
		pehkui: Pehkui 1.7.0+20w51a
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		satin: Satin 1.5.1
		stacc: Stacc 1.0.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.2-hotfix
		waystones: Waystones 1.0.10
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x AMD FX(tm)-4300 Quad-Core Processor
```
